[Feature : 2D Map] Colour tour graph based on power values
mytourbook/mytourbook pull request #1070
Opened 2023-04-16 16:23 UTC by cyc1ingsir

I hoped this would be a good first (or second, to be precise) time issue for a PR.
So I had a go.
Unfortunately, my setup is completely broken, so I'm not able to run MT within Eclipse any longer, nor is `mvn  install` working for me.

I'm still hoping, I discovered every place within the code base, where an addition is needed.
May I kindly ask for a review and guidance on how I may improve this code.

2023-04-17 07:07 UTC, wolfgang-ch requested changes
For your "first" PR there are a few issues.

I found no issues for the code itself, but [here](https://github.com/mytourbook/mytourbook/discussions/919) are a few rules which I update infrequently.

2023-04-18 20:29 UTC, cyc1ingsir commented
I hope to have covered everything by the last commits.
Eclipse keeps to rearranging some code in some of the changed files on me and being used to use a completely different IDE (at work), I couldn't find a way to preventing it doing so, swiftly. :-(
So I just hope, the commits include all the necessary changes but also not more changes than needed.

2023-04-19 05:03 UTC, wolfgang-ch commented
> Eclipse keeps to rearranging some code in some of the changed files on me and being used to use a completely different IDE (at work), I couldn't find a way to preventing it from doing so, swiftly. :-(

Have you setup the code formatting as described in https://mytourbook.sourceforge.io/mytourbook/index.php/development/dev-code-style/code-style

2023-04-19 05:28 UTC, wolfgang-ch commented
A very colorful track when power values are computed and not from a device.

The power max value of 800 Watt which you have set, was a little bit too high for me

![image](https://user-images.githubusercontent.com/1283445/232974878-cb72b5d1-8275-4a1a-8bff-776ab1c6dc2e.png)

2023-04-19 05:54 UTC, wolfgang-ch approved these changes
There is no need for further modifications

2023-04-19 05:54 UTC, wolfgang-ch commented on bundles/net.tourbook/src/net/tourbook/map2/view/SlideoutMap2_TourColors.java
> +   private Button   _chkShowInChartToolbar_Power;
This comment is for the following line in this file

` * Copyright (C) 2005, 2021 Wolfgang Schramm and Contributors`

When you modify a file you may also check, that the copyright year is updated. This is not dramatically and I also forget it sometimes.

2023-04-19 05:54 UTC, merged