[MAP25] [WIP] Compassrose
mytourbook/mytourbook pull request #899
Opened 2022-07-21 09:36 UTC by telemaxx

2022-07-21 13:02 UTC, wolfgang-ch requested changes

2022-07-21 13:10 UTC, wolfgang-ch commented
I'm wondering why this PR has 800 changes in Github but only a few in Eclipse. 

800 changes makes the website very slow in the browser when selecting/searching a modified file

![image](https://user-images.githubusercontent.com/1283445/180221301-939c39b4-33a1-41f2-82fe-145a4669cb3c.png)

![image](https://user-images.githubusercontent.com/1283445/180221328-cddbac36-8c89-405e-b374-0066c9240d86.png)

2022-07-21 13:17 UTC, wolfgang-ch commented
This PR is for `mytourbook:tm-map25` but it is not necessary any more that you update this/your branch because in Eclipse a PR can now be easily fetched from Github, just copy the url into the clipboard and select this action

![image](https://user-images.githubusercontent.com/1283445/180222656-16a36756-e552-4f18-9bf6-e12552890b99.png)


![image](https://user-images.githubusercontent.com/1283445/180222130-c86c8e4d-de86-4260-92df-048acaa58310.png)

2022-07-21 14:04 UTC, telemaxx commented on bundles/net.tourbook/src/net/tourbook/map25/Map25View.java
> +   private static final String           STATE_IS_LAYER_COMPASS_ROSE_VISIBLE     = "STATE_IS_LAYER_COMPASS_ROSE_VISIBLE";        //$NON-NLS-1$
done

2022-07-21 14:16 UTC, telemaxx commented on bundles/net.tourbook/src/net/tourbook/map25/Map25App.java
> +   private void updateLayer_CompassRose() {
removed

2022-07-21 14:17 UTC, telemaxx commented
> I'm wondering why this PR has 800 changes in Github but only a few in Eclipse

yes, maybe i should have create a new fresh branch from main.
tm-map25 was old...

2022-07-21 14:26 UTC, telemaxx commented
> but it is not necessary any more

hmm complicate, maybe due the weather my brain is overheating today.

next PR i try...

2022-07-22 04:50 UTC, wolfgang-ch commented
> > but it is not necessary any more
> 
> hmm complicate, maybe due the weather my brain is overheating today.
> 
> next PR i try...

Just create the PR against the `main` branch but your branch has first to be merged with `main`, then there is only a difference between `main` and your branch

2022-07-22 05:21 UTC, wolfgang-ch commented
After I've resetted `mytourbook:tm-map25` to the commit where you created the PR, now only 11 modified files are available which makes me happier than merging 800 files.

So you created the PR correctly but I did it not the old way.

In the future, do it simpler as described above https://github.com/mytourbook/mytourbook/pull/899#issuecomment-1192179158

![image](https://user-images.githubusercontent.com/1283445/180367943-560c2e6a-1e0a-447e-abb6-51554f30d816.png)

2022-07-22 05:45 UTC, wolfgang-ch commented on bundles/net.tourbook/src/net/tourbook/map25/layer/marker/MarkerShape.java
> +   COMPASS,
The compassrose should be similar like in the 3D map

1. Position should be in the top right corner
2. It should not be so much tilt like the map

Position (1.)

![image](https://user-images.githubusercontent.com/1283445/180370785-726e809e-deee-496f-b4c3-75107dee1578.png)

Tilt (2.)

![image](https://user-images.githubusercontent.com/1283445/180371070-157c84d6-af13-4229-8a45-5127b056df9a.png)

2022-08-01 06:26 UTC, wolfgang-ch commented
Implemented in https://github.com/mytourbook/mytourbook/commit/5d4864665c5df31ba078c91fc72ba2e4d351dfd1

2022-08-01 06:26 UTC, closed without merging